"""empty message

Revision ID: db02924426e8
Revises: 61d17a59ef74
Create Date: 2022-03-03 20:44:48.357651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db02924426e8'
down_revision = '61d17a59ef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('modificationstate', sa.Boolean(), nullable=True))
    op.add_column('content', sa.Column('modificationdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'modificationdate')
    op.drop_column('content', 'modificationstate')
    # ### end Alembic commands ###
