"""empty message

Revision ID: e9e8d7aa0d83
Revises: 8cf285e5cae5
Create Date: 2022-03-03 19:59:18.755227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e8d7aa0d83'
down_revision = '8cf285e5cae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('content', sa.Column('c2id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content', 'category2', ['c2id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'c2id')
    op.drop_table('category2')
    # ### end Alembic commands ###
